mgr: api_docs.py: Use view().get_view_name() instead of metadata
Attempting to access view().metadata(None)['name'] results in
"AttributeError: 'super' object has no attribute 'metadata'".

Signed-off-by: Tim Serong <tserong@suse.com>